#!/bin/bash

#clean up previous job (just in case)
rm -f finished

# remove surface directory
rm -rf surfaces

echo "counting files"
NUMFILES=`python numfiles.py`
echo "there are $NUMFILES files" 
echo "starting main"

singularity exec -e docker://brainlife/pythonvtk:1.2 ./main.py

count=$(ls surfaces/* | wc -l)
if [ "$count" == "$NUMFILES" ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
